/* Sound Clash — song curation review tool (vanilla JS, runs from file://).
 *
 * Reads window.CANDIDATES (generated by verify.py into candidates.js) and lets
 * a human preview each song in the SAME YouTube IFrame player the game uses,
 * fix title/artist/genre/start_time inline, approve or reject, and export the
 * approved rows as an upload-ready CSV. Decisions + edits persist in
 * localStorage keyed by youtube_id, so review can span multiple sittings.
 */

// The 11 genre slugs the importer accepts.
const GENRES = [
  ["rock", "Rock"],
  ["pop", "Pop"],
  ["hip-hop", "Hip-Hop"],
  ["electronic", "Electronic"],
  ["soundtracks", "Soundtracks"],
  ["israeli-pop", "Israeli Pop"],
  ["israeli-cover", "Israeli Cover"],
  ["israeli-rock-pop", "Israeli Rock-Pop"],
  ["israeli-rap-hip-hop", "Israeli Rap & Hip-Hop"],
  ["mizrahit", "Mizrahit"],
  ["israeli-soundtracks", "Israeli Soundtracks"],
];
const VALID_SLUGS = new Set(GENRES.map(([slug]) => slug));
const SOUNDTRACK_SLUGS = new Set(["soundtracks", "israeli-soundtracks"]);

const STORE_KEY = "song-curation:v1";
const candidates = Array.isArray(window.CANDIDATES) ? window.CANDIDATES : [];

let store = {};
try {
  store = JSON.parse(localStorage.getItem(STORE_KEY) || "{}");
} catch {
  store = {};
}
function saveStore() {
  localStorage.setItem(STORE_KEY, JSON.stringify(store));
}
function rec(id) {
  return store[id] || (store[id] = {});
}
// Effective (override-or-default) accessors.
function effTitle(c) {
  const r = store[c.youtube_id] || {};
  return r.title != null ? r.title : c.title || "";
}
function effArtist(c) {
  const r = store[c.youtube_id] || {};
  return r.artist != null ? r.artist : c.artist || "";
}
function effStart(c) {
  const r = store[c.youtube_id] || {};
  const v = r.start_time != null ? r.start_time : c.start_time;
  return Number.isFinite(v) ? v : 0;
}
function effGenres(c) {
  const r = store[c.youtube_id] || {};
  const g = r.genres != null ? r.genres : c.genres || [];
  return g.filter((s) => VALID_SLUGS.has(s));
}
function decision(id) {
  return (store[id] || {}).decision || null;
}

// ---- elements ----
const cardsEl = document.getElementById("cards");
const countsEl = document.getElementById("counts");
const emptyEl = document.getElementById("empty");
const searchEl = document.getElementById("search");
const nowPlayingEl = document.getElementById("now-playing");
const setStartBtn = document.getElementById("set-start");
const playerTimeEl = document.getElementById("player-time");
const playerErrorEl = document.getElementById("player-error");

let currentFilter = "all";
let activeId = null;

// ---- YouTube player ----
let player = null;
let playerReady = false;
function initPlayer() {
  player = new YT.Player("player", {
    width: "100%",
    height: "100%",
    host: "https://www.youtube-nocookie.com",
    playerVars: { rel: 0, modestbranding: 1, playsinline: 1, controls: 1 },
    events: {
      onReady: () => {
        playerReady = true;
      },
      onError: (e) => onPlayerError(e.data),
    },
  });
}
if (window.YT && window.YT.Player) {
  initPlayer();
} else {
  window.onYouTubeIframeAPIReady = initPlayer;
}

function onPlayerError(code) {
  const map = {
    2: "Invalid video id.",
    5: "HTML5 player error.",
    100: "Video removed or private.",
    101: "Embedding disabled by owner — unusable in-game.",
    150: "Embedding disabled by owner — unusable in-game.",
  };
  const msg = map[code] || `Player error ${code}.`;
  playerErrorEl.textContent = `⚠ ${msg}`;
  if (activeId) {
    rec(activeId).errorCode = code;
    saveStore();
    const card = cardsEl.querySelector(`.card[data-id="${cssEsc(activeId)}"]`);
    if (card) renderBadges(card, byId(activeId));
  }
}

function loadVideo(c) {
  if (!playerReady || !player) {
    nowPlayingEl.textContent = "Player still loading — try again in a moment.";
    return;
  }
  activeId = c.youtube_id;
  playerErrorEl.textContent = "";
  setStartBtn.disabled = false;
  nowPlayingEl.innerHTML = `▶ <strong>${escHtml(effTitle(c))}</strong> — ${escHtml(effArtist(c))} <span class="player-time">(start ${effStart(c)}s)</span>`;
  player.loadVideoById({ videoId: c.youtube_id, startSeconds: effStart(c) });
  markActiveCard();
}

function markActiveCard() {
  cardsEl.querySelectorAll(".card.active").forEach((el) => el.classList.remove("active"));
  if (activeId) {
    const card = cardsEl.querySelector(`.card[data-id="${cssEsc(activeId)}"]`);
    if (card) card.classList.add("active");
  }
}

setStartBtn.addEventListener("click", () => {
  if (!player || !activeId) return;
  const t = Math.max(0, Math.round(player.getCurrentTime() || 0));
  rec(activeId).start_time = t;
  saveStore();
  const input = cardsEl.querySelector(
    `.card[data-id="${cssEsc(activeId)}"] input[name="start_time"]`,
  );
  if (input) input.value = String(t);
  playerTimeEl.textContent = `set start → ${t}s`;
});

// Live current-time readout while previewing.
setInterval(() => {
  if (player && playerReady && activeId && typeof player.getCurrentTime === "function") {
    const state = typeof player.getPlayerState === "function" ? player.getPlayerState() : -1;
    if (state === 1 || state === 2) {
      playerTimeEl.textContent = `now ${Math.floor(player.getCurrentTime())}s`;
    }
  }
}, 500);

// ---- rendering ----
function byId(id) {
  return candidates.find((c) => c.youtube_id === id);
}

function matches(c) {
  if (currentFilter === "approved" && decision(c.youtube_id) !== "approved") return false;
  if (currentFilter === "rejected" && decision(c.youtube_id) !== "rejected") return false;
  if (currentFilter === "pending" && decision(c.youtube_id) != null) return false;
  if (currentFilter === "flagged") {
    const flagged = (c.match_status && c.match_status !== "ok") || !c.valid || rec(c.youtube_id).errorCode;
    if (!flagged) return false;
  }
  const q = searchEl.value.trim().toLowerCase();
  if (q) {
    const hay = [
      effTitle(c),
      effArtist(c),
      c.oembed_title || "",
      c.oembed_author || "",
      effGenres(c).join(" "),
    ]
      .join(" ")
      .toLowerCase();
    if (!hay.includes(q)) return false;
  }
  return true;
}

function statusBadge(c) {
  if (c.valid === false) return { cls: "bad", text: "INVALID ID" };
  switch (c.match_status) {
    case "ok":
      return { cls: "ok", text: "match ✓" };
    case "check-title":
      return { cls: "warn", text: "title?" };
    case "check-artist":
      return { cls: "warn", text: "artist?" };
    case "mismatch":
      return { cls: "bad", text: "mismatch?" };
    case "duplicate":
      return { cls: "warn", text: "already in catalog" };
    default:
      return { cls: "", text: c.match_status || "unverified" };
  }
}

function renderBadges(card, c) {
  const wrap = card.querySelector(".badges");
  const parts = [];
  const sb = statusBadge(c);
  parts.push(`<span class="badge ${sb.cls}">${escHtml(sb.text)}</span>`);
  if (c.source) parts.push(`<span class="badge">${escHtml(c.source)}</span>`);
  const err = rec(c.youtube_id).errorCode;
  if (err) parts.push(`<span class="badge bad">play error ${err}</span>`);
  wrap.innerHTML = parts.join("");
}

function cardHtml(c, idx) {
  const id = c.youtube_id;
  const d = decision(id);
  const cls = ["card", d === "approved" ? "approved" : "", d === "rejected" ? "rejected" : ""]
    .filter(Boolean)
    .join(" ");
  const sel = new Set(effGenres(c));
  const genreBoxes = GENRES.map(
    ([slug, label]) =>
      `<label><input type="checkbox" name="genre" value="${slug}" ${sel.has(slug) ? "checked" : ""}/> ${label}</label>`,
  ).join("");
  const thumb = c.thumbnail || `https://i.ytimg.com/vi/${id}/hqdefault.jpg`;
  const watch = `https://www.youtube.com/watch?v=${id}`;
  return `
  <div class="${cls}" data-id="${escAttr(id)}">
    <div class="thumb-wrap">
      <img class="thumb" src="${escAttr(thumb)}" loading="lazy" alt="thumbnail" data-act="load" />
      <span class="idx">#${idx + 1}</span>
    </div>
    <div class="card-body">
      <div class="field-row"><label>Title</label><input type="text" name="title" value="${escAttr(effTitle(c))}" /></div>
      <div class="field-row"><label>Artist</label><input type="text" name="artist" value="${escAttr(effArtist(c))}" /></div>
      <div class="oembed">
        YouTube says: <b>${escHtml(c.oembed_title || "—")}</b><br />
        channel: ${escHtml(c.oembed_author || "—")} ·
        <a class="yt-link" href="${escAttr(watch)}" target="_blank" rel="noreferrer">${escHtml(id)} ↗</a>
      </div>
      <div class="badges"></div>
      <div class="genres">${genreBoxes}</div>
      <div class="card-actions">
        <div class="field-row" style="flex:0 0 auto"><label>Start</label><input type="number" name="start_time" min="0" value="${effStart(c)}" /></div>
        <button type="button" class="load" data-act="load">▶ Load</button>
        <button type="button" class="approve" data-act="approve">Approve</button>
        <button type="button" class="reject" data-act="reject">Reject</button>
      </div>
    </div>
  </div>`;
}

function render() {
  emptyEl.classList.toggle("hidden", candidates.length > 0);
  const visible = candidates.filter(matches);
  cardsEl.innerHTML = visible.map((c) => cardHtml(c, candidates.indexOf(c))).join("");
  cardsEl.querySelectorAll(".card").forEach((card) => renderBadges(card, byId(card.dataset.id)));
  markActiveCard();
  renderCounts();
}

function renderCounts() {
  let approved = 0,
    rejected = 0,
    pending = 0,
    flagged = 0;
  for (const c of candidates) {
    const d = decision(c.youtube_id);
    if (d === "approved") approved++;
    else if (d === "rejected") rejected++;
    else pending++;
    if ((c.match_status && c.match_status !== "ok") || c.valid === false || rec(c.youtube_id).errorCode)
      flagged++;
  }
  countsEl.innerHTML =
    `<span>total <b>${candidates.length}</b></span>` +
    `<span>✓ approved <b>${approved}</b></span>` +
    `<span>✕ rejected <b>${rejected}</b></span>` +
    `<span>• pending <b>${pending}</b></span>` +
    `<span>⚑ flagged <b>${flagged}</b></span>`;
}

// ---- events (delegated) ----
cardsEl.addEventListener("click", (e) => {
  const card = e.target.closest(".card");
  if (!card) return;
  const id = card.dataset.id;
  const c = byId(id);
  const act = e.target.dataset.act;
  if (act === "load") {
    loadVideo(c);
  } else if (act === "approve") {
    rec(id).decision = decision(id) === "approved" ? null : "approved";
    saveStore();
    render();
  } else if (act === "reject") {
    rec(id).decision = decision(id) === "rejected" ? null : "rejected";
    saveStore();
    render();
  }
});

cardsEl.addEventListener("input", (e) => {
  const card = e.target.closest(".card");
  if (!card) return;
  const id = card.dataset.id;
  const name = e.target.name;
  if (name === "title") rec(id).title = e.target.value;
  else if (name === "artist") rec(id).artist = e.target.value;
  else if (name === "start_time") rec(id).start_time = Math.max(0, parseInt(e.target.value, 10) || 0);
  else return;
  saveStore();
});

cardsEl.addEventListener("change", (e) => {
  if (e.target.name !== "genre") return;
  const card = e.target.closest(".card");
  const id = card.dataset.id;
  const selected = Array.from(card.querySelectorAll('input[name="genre"]:checked')).map(
    (b) => b.value,
  );
  rec(id).genres = selected;
  saveStore();
});

document.getElementById("filters").addEventListener("click", (e) => {
  if (e.target.tagName !== "BUTTON") return;
  currentFilter = e.target.dataset.filter;
  document.querySelectorAll("#filters button").forEach((b) => b.classList.remove("active"));
  e.target.classList.add("active");
  render();
});

searchEl.addEventListener("input", render);

document.getElementById("export-csv").addEventListener("click", exportCsv);
document.getElementById("reset").addEventListener("click", () => {
  if (!confirm("Clear ALL approve/reject decisions and inline edits? Cannot be undone.")) return;
  store = {};
  saveStore();
  activeId = null;
  render();
});

function exportCsv() {
  const approved = candidates.filter((c) => decision(c.youtube_id) === "approved");
  if (approved.length === 0) {
    alert("No songs approved yet.");
    return;
  }
  const header = ["title", "artist", "youtube_id", "start_time", "is_soundtrack", "genres"];
  const lines = [header.join(",")];
  const problems = [];
  for (const c of approved) {
    const genres = effGenres(c);
    if (genres.length === 0) problems.push(`${effTitle(c)} (${c.youtube_id}): no genre`);
    const isSoundtrack = genres.some((s) => SOUNDTRACK_SLUGS.has(s));
    lines.push(
      [
        effTitle(c),
        effArtist(c),
        c.youtube_id,
        effStart(c),
        isSoundtrack ? "true" : "false",
        genres.join(";"),
      ]
        .map(csvCell)
        .join(","),
    );
  }
  if (problems.length && !confirm(`${problems.length} approved song(s) have no genre and will be rejected by the importer:\n\n${problems.join("\n")}\n\nExport anyway?`))
    return;
  const blob = new Blob(["﻿" + lines.join("\r\n") + "\r\n"], {
    type: "text/csv;charset=utf-8",
  });
  const a = document.createElement("a");
  const stamp = new Date().toISOString().slice(0, 10);
  a.href = URL.createObjectURL(blob);
  a.download = `approved-songs-${stamp}.csv`;
  a.click();
  URL.revokeObjectURL(a.href);
}

// ---- helpers ----
function csvCell(v) {
  const s = String(v);
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}
function escHtml(s) {
  return String(s).replace(/[&<>]/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[m]);
}
function escAttr(s) {
  return String(s).replace(/[&<>"']/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[m]);
}
function cssEsc(s) {
  return window.CSS && CSS.escape ? CSS.escape(s) : String(s).replace(/["\\]/g, "\\$&");
}

render();
